### ISSUE TITLE
Export not found in three

### ISSUE THREAD

**Issue by LauferAlex** [nartc/angular-three#10]
Hi Team,

So we are trying to use angular-three to make some 3D visualization and we are trying to build a simple Skybox. For this purpose we are trying to import **ngt-sphere-geometry** and for that we are importing the **ThreeSphereBufferGeometryModule** and we are getting this error: 

![image](https://user-images.githubusercontent.com/86115165/137757062-6fb1f0ce-4047-4a79-81f2-1d328f76f8c2.png)

Code structure as follows:

_app.module.ts_
`import {ThreeSphereBufferGeometryModule} from "@angular-three/core/geometries";`

```
@NgModule({
  declarations: [
    AppComponent,
    ModelViewComponent
  ],
    imports: [
        ...
        ThreeSphereBufferGeometryModule,
    ],
  providers: [],
  bootstrap: [AppComponent]
})
```

_model-view-component.html_

```
<ngt-canvas
  [camera]='{position: [1, 1, 3], fov: 90, near: 0.1, far: 1000}'
  [scene]="{ fog: ['000000', 1, 15000] | fog }"
  (created)='$event.gl.setClearColor("gray")'
  [shadows]="true"
>
  <ngt-mesh>
    <ngt-sphere-geometry [args]="[500, 60,40]" #skybox> </ngt-sphere-geometry>
  </ngt-mesh>
  <ngt-grid-helper o3d></ngt-grid-helper>
</ngt-canvas>
```

We only get this error when trying to import any buffer geometry into the scene. Thanks for the help in advance!

**Comment by nartc** [comment]
Can you provide THREE version? I'll sync everything back up either today or tomorrow

**Comment by nartc** [comment]
@LauferAlex thank you for providing the information. Latest `three` has moved some symbols from `three` core module to `examples/*` which breaks some of the imports. I'll push a fix as soon as EOD tomorrow. Thank you for understanding
