### ISSUE TITLE
[Feature] Add support for cannon RaycastVehicle

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#100]
I'm converting the cannon [raycast vehicle example](https://github.com/pmndrs/cannon-es/blob/master/examples/raycast_vehicle.html) and [rigid vehicle example](https://github.com/pmndrs/cannon-es/blob/master/examples/rigid_vehicle.html)

These features seem to be missing from the @angular-three/cannon.

**Comment by nartc** [comment]
RaycastVehicle is available on the Cannon Worker API but RigidVehicle is not. I'll be adding RaycastVehicle soon.

**Comment by nartc** [comment]
Added in v5
