### ISSUE TITLE
[Feature] Disable helper functions without removing attribute

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#104]
While working on new [trigger example](https://ng3cannon.z9.web.core.windows.net?example=trigger), I added the ngtSpotLightHelper to a spot light to help visualize where the spot light was pointing.

```html
<ngt-spot-light #spot (ready)="off(spot)" name="spot" 
  ngtSpotLightHelper castShadow 
  [position]="[1, 10, -2]" angle="0.3" penumbra="1" 
  [target]="sphere.instance.value">
</ngt-spot-light>
```
After getting everything working, I wanted to disable the helper.  However, there doesn't appear to be a way to do this without completely removing it from the ngt-spot-light element.

This feature request is to ask for a way to disable helper directives without removing from the code.

**Comment by IRobot1** [comment]
One solution is to pass the helper into the ready function and set visible to false.  Set visible to true when needed.
```html
<ngt-spot-light #spot (ready)="off(spot, helper)" 
  #helper="ngtSpotLightHelper" ngtSpotLightHelper 
```
```ts
  off(spot: NgtSpotLight, helper: NgtSpotLightHelper) {
    helper.instance.value.visible = false;
  }
```

**Comment by nartc** [comment]
@IRobot1 beta-18 exposes `helperVisible` as an Input.
