### ISSUE TITLE
getting error in angular-three, is only imported `NgtCanvasModule`

### ISSUE THREAD

**Issue by Sohail-Fladdra** [nartc/angular-three#122]
getting this error: 
ERROR in node_modules/@angular-three/core/lib/types.d.ts:16:64 - error TS1005: ';' expected.

16 export declare type AnyAbstractConstructor<TObject> = abstract new (...args: any[]) => TObject;
                                                                  ~~~
node_modules/@angular-three/core/lib/types.d.ts:16:69 - error TS1109: Expression expected.

16 export declare type AnyAbstractConstructor<TObject> = abstract new (...args: any[]) => TObject;
                                                                       ~~~
node_modules/@angular-three/core/lib/types.d.ts:16:82 - error TS1011: An element access expression should take an argument.     

16 export declare type AnyAbstractConstructor<TObject> = abstract new (...args: any[]) => TObject;

node_modules/@angular-three/core/lib/types.d.ts:16:83 - error TS1005: ';' expected.

16 export declare type AnyAbstractConstructor<TObject> = abstract new (...args: any[]) => TObject;
                                                                                     ~
node_modules/@angular-three/core/lib/types.d.ts:16:85 - error TS1128: Declaration or statement expected.

16 export declare type AnyAbstractConstructor<TObject> = abstract new (...args: any[]) => TObject;

**Comment by IRobot1** [comment]
Did you follow [installation instructions](https://angular-three.netlify.app/docs/getting-started/installation)?

**Comment by nartc** [comment]
thanks @IRobot1 I'll update that to 0.140 asap
