### ISSUE TITLE
Support for threejs r141

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#125]
[r141](https://github.com/mrdoob/three.js/releases/tag/r141) fixes a bug in VR teleport.

**Comment by nartc** [comment]
@IRobot1 the demo site is using r141 already but I'm noticing some performance issue. Can you go to https://angular-three.netlify.app/examples/home and see if the physics examples run at 60fps?

**Comment by IRobot1** [comment]
They all run 60fps for me

**Comment by nartc** [comment]
@IRobot1 I'll cut a release later today to bump 141. Thanks
