### ISSUE TITLE
 Error: export 'XRRigidTransform' (imported as 'XRRigidTransform') was not found in 'three'

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#126]
I'm trying to convert the following [VR teleport example](https://github.com/mrdoob/three.js/blob/master/examples/webxr_vr_teleport.html) to NGT. 

Build fails when referencing XRRigidTransform from Angular project

```ts
import { XRInputSource, XRRigidTransform } from "three";
...
      const offsetPosition = { x: 0, y: 0, z: 0, w: 1 };
      const offsetRotation = new Quaternion();
      const transform = new XRRigidTransform(offsetPosition, offsetRotation);
```

XRInputSource (interface) is found, but XRRigidTransform (class) is not.

 - Browser: [Edge]
 - NGT [5.4.0]
 - Three.js version: [r140 or r141]

Any suggestions is appreciated.

**Comment by nartc** [comment]
`XRRigidTransform` is WebXR API and not part of three APIs. https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform

**Comment by IRobot1** [comment]
Understood.  If you add the following code to any sandbox project

```ts
        const offsetPosition = { x: 0, y: 0, z: 0, w: 1 };
        const offsetRotation = { x: 0, y: 0, z: 0, w: 1 };
        const transform = new XRRigidTransform(offsetPosition, offsetRotation);
```

Can you confirm you get the following error?  I'm using Visual Studio Professional.

![image](https://user-images.githubusercontent.com/25032599/170909652-6c725d28-1c55-4459-a536-9b41cd327c46.png)

**Comment by IRobot1** [comment]
Why do you close an issue before the person asking the question has confirmed your answer?  That really bugs me when you do that.

**Comment by nartc** [comment]
Because there's no actionable item from the library's perspective. There is nothing that I can add to Angular Three API to fix your issue. If you like, you can convert this to a discussion instead. As a maintainer, Issue shows the number of issues whereas Discussion does not, it gives me less stress on maintaining the library.
