### ISSUE TITLE
NgtPrimitiveModule not working. "'ngt-primitve' is not a known element"

### ISSUE THREAD

**Issue by AkramFaiz** [nartc/angular-three#136]
Hi I am new to NGT. 

I am facing the following issue. It would be very helpful if you can guide me.

Module imported: import { NgtPrimitiveModule } from "@angular-three/core/primitive"; imports: [....,NgtPrimitiveModule]  Ref: https://angular-three.netlify.app/docs/core/objects

Error: 'ngt-primitve' is not a known element:

**Comment by IRobot1** [comment]
Its ngt-primitive not ngt-primitve.  Don't feel back, it took me an hour of scratching my head before I spotted the spelling mistake.

**Comment by AkramFaiz** [comment]
Thanks a lot. My bad. 
Now I am facing issue with - import { NgtSobaOrbitControlsModule } from "@angular-three/soba/controls";
Can you please guide me with this.

**Comment by IRobot1** [comment]
I can repeat these errors with your project, but haven't found a way clear it.

What's odd is that I've never run into this problem with any of my own projects that include SOBA and orbit control.

**Comment by AkramFaiz** [comment]
Thanks  IRobot1 .
