### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by marcindz88** [nartc/angular-three#138]
Hello,
I can see that the version of Angular has been updated to 14 in the project, but the required peer dependencies are still `^13.0.0`. 
Could you update it or allow both versions 13 and 14 by specifying a range `>=13.0.0 < 15.0.0`?

Currently, I have to install with `--legacy-peer-deps` which is annoying, as the lib was updated...

Thanks

**Comment by IRobot1** [comment]
@types/three is now available for v142

**Comment by nartc** [comment]
Angular 14 and 0.142 support is coming, probably sometimes next week

**Comment by nartc** [comment]
Released 6.0.0

**Comment by marcindz88** [comment]
Thanks :)

**Comment by marcindz88** [comment]
@nartc
`Could not resolve dependency:
npm ERR! peer three@"~0.141.0 | ~0.142.0" from @angular-three/core@6.0.0`
Could you change it to range or correct alternation sign (||)?
