### ISSUE TITLE
THREE.WebGLRenderer: Context Lost.

### ISSUE THREAD

**Issue by plusnia-pgs** [nartc/angular-three#140]
Hi,
There is a problem with newest version.
https://stackblitz.com/edit/angular-ivy-gqtdqy?file=src/app/app.component.html

**Comment by plusnia-pgs** [comment]
Another problem
https://stackblitz.com/edit/angular-ivy-ykcyxc?file=src/app/app.module.ts

**Comment by nartc** [comment]
Hi, the `Context Lost.` problem isn't reliable on Stackblitz or Codesandbox. The problem in this Stackblitz is the parent element (`body` and `html` in this case) has no height. Give them `height: 100%` using `style.css` will show the cube
