### ISSUE TITLE
6.0.0-beta

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#141]
Upgrading the [ng3-cannon-demo](https://github.com/IRobot1/ng3-cannon-template) gives the following problems

Compile time
* Looks like NgtColorPipeModule,  NgtVectorPipeModule have been removed.  
I didn't use Vector pipe, but I did use Color.  Are these no longer provided?  I was able to work-around color pipe being removed.

* Can't bind to 'parameters' since it isn't a known property of 'ngt-mesh-standard-material'. 
Has support for parameters been dropped from ngt-mesh-XXX-material?  I was able to work-around.

Runtime
Error: NG0200: Circular dependency in DI detected for NgtColorAttribute.
Its not specific to NgtColorAttribute.  Any NGT object inside <ngt-canvas> results in this error.  I'll see if this happens in other projects first

**Comment by IRobot1** [comment]
The runtime Error: NG0200: Circular dependency in DI detected... when away after upgrading to Angular 14.1

**Comment by IRobot1** [comment]
Upgrading [ng3-vr-examples ](https://github.com/IRobot1/ng3-vr-examples) gives the following problems

Compile time
* Module '"@angular-three/core"' has no exported member 'makeVector3'.
Looks like makeVector3 was removed and now requires using make(T, x).  I was able to work-around.
[Documentation will need tweaking](https://angular-three.netlify.app/docs/core/additional-exports) as a result.

Runtime
* Error: Cannot find module 'three'  at webpackMissingModule (angular-three-soba-cameras.mjs:168:1)
This problem went away after upgrading to Angular 14.1.

**Comment by IRobot1** [comment]
Upgrading to [ng3-ar-examples](https://github.com/IRobot1/ng3-ar-examples) had similar issues, but was able to work-around them all.

**Comment by IRobot1** [comment]
List of [breaking changes](https://github.com/nartc/angular-three/blob/main/libs/core/breaking.md)

**Comment by nartc** [comment]
Thank you for trying it out.
- `NgtColorPipe` and `NgtVector*Pipe` are definitely removed. Documented in docs (haven't pushed)
- `[parameters]` on Materials are removed (deprecated as of last version). Documented in docs (haven't pushed)
- `makeColor` and `makeVector*` are removed in favor of a single `make()`. Documented in docs (haven't pushed)

Cool. I'm working towards updating docs atm.
