### ISSUE TITLE
Missing LUT3DEffect error

### ISSUE THREAD

**Issue by alcaponepl** [nartc/angular-three#142]
Hi,
I have an error with the newest version:

"dependencies": {
    "@angular-three/cannon": "^5.5.0",
    "@angular-three/controls": "^2.0.0-beta.8",
    "@angular-three/core": "^5.5.0",
    "@angular-three/postprocessing": "^5.5.0",
    "@angular-three/schematics": "^5.5.0",
    "@angular-three/soba": "^5.5.0",
    "@angular/animations": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/forms": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/router": "^14.1.0",
    "rxjs": "~7.5.0",
    "three": "^0.142.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.1.0",
    "@angular/cli": "^14.1.0",
    "@angular/compiler-cli": "^14.1.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "@types/three": "~0.141.0",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "postprocessing": "^6.28.4",
    "typescript": "~4.6.2"
  }

./node_modules/@angular-three/postprocessing/fesm2020/angular-three-postprocessing-effects.mjs:1802:11-22 - Error: export 'LUT3DEffect' (imported as 'LUT3DEffect') was not found in 'postprocessing' (possible exports: AdaptiveLuminanceMaterial, AdaptiveLuminancePass, BlendFunction, BlendMode, BloomEffect, BlurPass, BokehEffect, BokehMaterial, BrightnessContrastEffect, ChromaticAberrationEffect, CircleOfConfusionMaterial, ClearMaskPass, ClearPass, ColorAverageEffect, ColorChannel, ColorDepthEffect, ColorEdgesMaterial, ConvolutionMaterial, CopyMaterial, CopyPass, DepthComparisonMaterial, DepthCopyMaterial, DepthCopyMode, DepthCopyPass, DepthDownsamplingMaterial, DepthDownsamplingPass, DepthEffect, DepthMaskMaterial, DepthOfFieldEffect, DepthPass, DepthPickingPass, DepthSavePass, DepthTestStrategy, Disposable, DotScreenEffect, EdgeDetectionMaterial, EdgeDetectionMode, Effect, EffectAttribute, EffectComposer, EffectMaterial, EffectPass, GammaCorrectionEffect, GlitchEffect, GlitchMode, GodRaysEffect, GodRaysMaterial, GridEffect, HueSaturationEffect, Initializable, KawaseBlurMaterial, KawaseBlurPass, KernelSize, LUT3dlLoader, LUTCubeLoader, LUTEffect, LUTOperation, LambdaPass, LookupTexture, LookupTexture3D, LuminanceMaterial, LuminancePass, MaskFunction, MaskMaterial, MaskPass, NoiseEffect, NoiseTexture, NormalPass, OutlineEdgesMaterial, OutlineEffect, OutlineMaterial, OverrideMaterialManager, Pass, PixelationEffect, PredicationMode, RawImageData, RealisticBokehEffect, RenderPass, Resizable, Resizer, Resolution, SMAAAreaImageData, SMAAEffect, SMAAImageGenerator, SMAAImageLoader, SMAAPreset, SMAASearchImageData, SMAAWeightsMaterial, SSAOEffect, SSAOMaterial, SavePass, ScanlineEffect, Section, Selection, SelectiveBloomEffect, SepiaEffect, ShaderPass, ShockWaveEffect, TetrahedralUpscaler, TextureEffect, Timer, ToneMappingEffect, ToneMappingMode, VignetteEffect, VignetteTechnique, WebGLExtension)

**Comment by IRobot1** [comment]
My guess is "three": "^0.142.0", is not supported by @angular-three 5.5.0 yet.  If you remove this entry, does it help?

**Comment by IRobot1** [comment]
Does upgrading to version 6.0.0 clear this error?

**Comment by alcaponepl** [comment]
I will check it and I will let you know

**Comment by alcaponepl** [comment]
work fine
