### ISSUE TITLE
QUESTION: Porting/Wrapping different physics engine "Force Directed layout in 3D" as a new component

### ISSUE THREAD

**Issue by proelf98** [nartc/angular-three#151]
I need to create a force directed layout  for a project to.  I've seen a project by the GitHub user Vasturiano [vasturiano/3d-force-graph](https://github.com/vasturiano/3d-force-graph), who used Three.js with this force layout [anvaka/ngraph.forcelayout3d](https://github.com/anvaka/ngraph.forcelayout3d) repository. I would like to have a component where it automatically created a force directed layout like from the Vasturiano [vasturiano/3d-force-graph](https://github.com/vasturiano/3d-force-graph) repository.

So I guess, when starting the porting process, it has to have a similar structure like your ported cannon libary. Would it be possible for you to elloborate your porting process? For instance I have few questions on my mind:
- what is needed for the porting?
- i've seen the libs/cannon is a seperated repository. Did you start with a regular Angular project or did you use some tools for porting?
- how would you begin with the porting process?

thank you in advance! Kind regards Noah :)

**Comment by IRobot1** [comment]
See [this example code](https://github.com/IRobot1/ng3-vr-examples/tree/master/src/examples/force-layout) of a force directed graph using angular-three to render the graph.  It shows both static and dynamic graphs. [DEMO here](https://ng3vr.z9.web.core.windows.net/?example=forcelayout)

Building this example, I noted that it works best for tree structured data (not a true graph).  With force layout, you have very little control of the layout when the data is a graph (multiple relationships per node).  Adding one more node can completely change the layout.

**Comment by proelf98** [comment]
Thanks man!
