### ISSUE TITLE
THREE.MeshStandardMaterial: 'Uniform' is not a property of this material issue

### ISSUE THREAD

**Issue by Hamedkabir** [nartc/angular-three#152]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/38732428/192477609-8d2eda77-3fbb-4e0c-b6e7-9ae9d926594f.png">

Hello
I get this warning and I have no idea how to fix this warning issue!
Thanks in advance
bests 
Hamed

**Comment by tomcatbuzz** [comment]
@Hamedkabir you should provide your code example for people to help troubleshoot your issue. Just showing an error is not going to get a response to solve your problem.
