### ISSUE TITLE
[FEATURE / QUESTION] SCAM / Lazy loading

### ISSUE THREAD

**Issue by BenLune** [nartc/angular-three#33]
Hi Chau !
**Is your feature request related to a problem? Please describe.**
I don't know if it's a problem or if I'm missing something... When I want to create a component, with its own Module with imports, my object is not displayed on the ThreeJS Scene, with no errors. If I declare this component in the main Module, with its imports then it works.

In order to get more isolated components, I would like to create a Module for each Component for them to be independent and easier usable/reusable, and also lazy loadable.
I plan also to be able to route some angular-three components, the way I dit it in a [demo](https://ngx-threejs-routing.netlify.app/) few months ago.

Thank you !

**Comment by nartc** [comment]
Oh no, can you make a sample reproduce?
