### ISSUE TITLE
[BUG] THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS - Can not showing file .GLB when using NgtGLTFLoaderService

### ISSUE THREAD

**Issue by kael2312** [nartc/angular-three#40]
**Scope**
- [x] core
- [ ] cannon
- [ ] postprocessing
- [x] soba

**Describe the bug**
I have this file need showing in my website: 
https://drive.google.com/file/d/1Sqtx97m7hLXjdBndYzR28EO0xbqK0DJn/view?fbclid=IwAR0ZYoeYFxGtiuxoD_MgzMWe_o1kjkOmiTuZW3_iV6O9xhOZ82vSO8klp0I](url)
It's oke when using https://gltf-viewer.donmccurdy.com/ for loading
But I can not showing this file in my website when using NgtGLTFLoaderService
You can see error in file attach

![error](https://user-images.githubusercontent.com/60740914/147183275-afe37387-8527-491d-b5e2-0cc2cb5f7ab8.PNG)

**Comment by nartc** [comment]
This seems to work in v5 now (probably due to THREE.js version)
