### ISSUE TITLE
[BUG] Soba Gizmo throws Exception when looking for 'scene' store

### ISSUE THREAD

**Issue by lukaszmac** [nartc/angular-three#41]
**Scope**
- [x] soba

**Describe the bug**
The angular-three-soba-abstractions gizmo implementation is currently throwing an exception because it doesn't find the 'scene' store. Instead, consider renaming or using the 'sceneOptions' store because that does appear to exist. Was the sceneOptions renamed recently and this part of the code wasn't updated?

**To Reproduce**
1. Follow the dual-cubes starting guide.
2. Add the code shown below to the ngt-canvas.
3. An exception is thrown in the console.

```
   <ngt-soba-gizmo-helper [margin]="[80,80]" [alignment]="'top-left'">
      <ngt-soba-gizmo-viewport
        
      ></ngt-soba-gizmo-viewport>
    </ngt-soba-gizmo-helper>
```

**Expected behavior**
We expect the viewport gizmo to show up like it does in the story demo on the website. It doesn't.

**Screenshots**
Below we can see the state of the store and it has a store called 'sceneOptions' but not 'scene' as the code requests.
![image](https://user-images.githubusercontent.com/10209428/147701536-331752ba-8866-4ebc-b890-3c2b2c8e5744.png)

**Comment by nartc** [comment]
Thank you for reporting!
