### ISSUE TITLE
ngt-group not working as expected when forgetting to import NgtGroupModule

### ISSUE THREAD

**Issue by lukaszmac** [nartc/angular-three#43]
**Scope**
- [x] core
- [ ] cannon
- [ ] postprocessing
- [ ] soba

**Describe the bug**
Using an ngt-group throws an exception when trying to add to a parent object.

**To Reproduce**
1. In an ngt-canvas, create any ngt-mesh. Notice that it works as expected.
2. Wrap the mesh in an ngt-group and you get the following exception:

`Uncaught TypeError: Cannot read properties of null (reading 'add')
    at NgtObject3dController._NgtObject3dController_addToParent (:4200/vendor.js:71004)
    at :4200/vendor.js:70993`

It seems like the add method might have been renamed to something else.

**Expected behavior**
We expect to be able to create a group for a collection of objects, as seen in the youtube video here:
https://youtu.be/RCgdXY9-Ir8?t=2587

The three.js documentation for the group is here:
https://threejs.org/docs/#api/en/objects/Group

**Comment by nartc** [comment]
I can't seem to reproduce this bug. Can you provide a reproduce sample?

**Comment by lukaszmac** [comment]
Yes, certainly. I have reproduced the bug here:
https://stackblitz.com/edit/angular-ivy-kb9mff?file=src%2Fapp%2Fapp.component.html

If you comment out the ngt-group then it works as expected, however, with the ngt-group, you get the reported error.

Maybe I am using ngt-group incorrectly, but then it would be very helpful to have some documentation or examples on how to use it. I struggled to find a reference for it.

### Working:
![image](https://user-images.githubusercontent.com/10209428/148512955-427f4ebe-1cf1-4756-9737-3fd0a827f7cf.png)

### Broken:
![image](https://user-images.githubusercontent.com/10209428/148513036-218fa549-5d71-415b-bbdb-288c443081b2.png)

**Comment by lukaszmac** [comment]
For easier reference, I have pasted the reproduction html here:

```
<div id="angular-three">
  <ngt-canvas [scene]="{ background: 'white' | color }">
    <ngt-ambient-light [intensity]="0.9"></ngt-ambient-light>

    <!-- If the ngt-group is commented out then it works. -->
    <!-- Uncomment the ngt-group below to reproduce the bug for: https://github.com/nartc/angular-three/issues/43 -->

   <!-- BUG HERE -->
   <ngt-group>
   <!-- BUG HERE -->

    <ngt-mesh>
      <ngt-box-geometry [args]="[1, 2, 3]"></ngt-box-geometry>
      <ngt-mesh-basic-material
        [parameters]="{ color: 'hotpink' | color }"
      ></ngt-mesh-basic-material>
    </ngt-mesh>

    <ngt-mesh>
      <ngt-box-geometry [args]="[3, 2, 1]"></ngt-box-geometry>
      <ngt-mesh-basic-material
        [parameters]="{ color: 'cornflowerblue' | color }"
      ></ngt-mesh-basic-material>
    </ngt-mesh>
   </ngt-group>
  </ngt-canvas>
```

**Comment by lukaszmac** [comment]
What is strange is that the demo from your youtube video works with the ngt-group. I wonder whether it's a regression in one of the more recent versions.
https://youtu.be/RCgdXY9-Ir8?t=2587
https://angular-ivy-wuxyst.stackblitz.io/

I have attempted to fork that repo and upgrade it to the current V2.17.0 to see if I can replicate. I am struggling a bit with that.
https://stackblitz.com/edit/angular-ivy-adgp9u
I am stuck on the missing dependency from somewhere. Maybe you have more luck.
![image](https://user-images.githubusercontent.com/10209428/148520061-6f5e5451-013e-460a-8ffc-6d31193f34c9.png)

**Comment by nartc** [comment]
@lukaszmac Thank you for providing the Stackblitz. Did you import `NgtGroupModule` from `@angular-three/core/group`?

**Comment by lukaszmac** [comment]
Oh dear! That was it. I didn't import the NgtGroupModule.

Thanks for the help with this. I should have checked that. Everything else has a module and so does this.
