### ISSUE TITLE
[BUG] Import NgtSobaOrbitControlsModule  error Cannot find name 'OffscreenCanvas'

### ISSUE THREAD

**Issue by b0yk0k4n3m** [nartc/angular-three#44]
**Scope**
- [ ] core
- [ ] cannon
- [ ] postprocessing
- [ x] soba

**Describe the bug**

**To Reproduce**
1. Import  NgtSobaOrbitControlsModule 
2. See error  Cannot find name 'OffscreenCanvas' ............

**Screenshots**
![image](https://user-images.githubusercontent.com/43802773/148794535-265c394b-f7eb-4d7d-bcce-62f038bd592b.png)

![image](https://user-images.githubusercontent.com/43802773/148794091-7028b951-5d72-4fae-8b1b-ad5fbe21f2c1.png)

**Comment by nartc** [comment]
@b0yk0k4n3m please turn on skipLibCheck in your root `tsconfig.json`. `three-stdlib` has issues with typings
