### ISSUE TITLE
[BUG]Zone-less is not exported error

### ISSUE THREAD

**Issue by cliffoksboel** [nartc/angular-three#45]
**Scope**
- [ x] core
- [ ] cannon
- [ ] postprocessing
- [ ] soba

**Describe the bug**
./node_modules/@angular-three/core/fesm2015/angular-three-core.mjs:6:0-92 - Error: Module not found: Error: Package path ./zone-less is not exported from package ./node_modules/@angular-three/core/node_modules/@rx-angular/cdk (see exports field in ./node_modules/@angular-three/core/node_modules/@rx-angular/cdk/package.json)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeroenMBooij** [comment]
I have the same issue. Does this error occur in every version of angular-three? If not, which version of angular-three do I have to install and which versions should the dependencies be?

**Comment by nartc** [comment]
Sorry for the delayed response. I have been working on releasing 4.0.0. This bug has been addressed in the latest major version. Please also check out the CHANGELOG for additional breaking changes info
