### ISSUE TITLE
Can't bind to 'getPhysicProps' 

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#51]
Trying to use code from [kinetic-cube](https://angular-three.netlify.app/?path=/docs/cannon-kinematic-cube--default) to understand how to enable physics. 
I've re-created the components, but getting the following error

Error: src/app/components/kinetic-box/spheres/app-spheres.component.html:4:21 - error NG8002: Can't bind to 'getPhysicProps' since it isn't a known property of 'ngt-instanced-mesh'.

```html
<ngt-instanced-mesh ngtPhysicSphere
                    [castShadow]="true"
                    [receiveShadow]="true"
                    [getPhysicProps]="getInstancedProps"
                    [args]="[number]">
...
</ngt-instanced-mesh>
```

What am I missing?

I'm going to try a much simpler example.

Any chance you could document some basic guidance on using @angular-three cannon?  It would go a long way to standing up a basic working example.

**Comment by nartc** [comment]
Please open a new issue if you run into any
