### ISSUE TITLE
ngt-group animateReady event not firing

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#56]
Application builds and runs without error.  However, animateReady event not firing on ngt-group.

**Comment by IRobot1** [comment]
To fix, 
import { NgtGroupModule } from '@angular-three/core/group';

import NgtGroupModule,

**Comment by nartc** [comment]
@IRobot1 keep in mind that Angular Three is built with modularization in mind. You would want to import the module associated with an element: `ngt-group` <-> `NgtGroupModule`, `ngt-mesh` <-> `NgtMeshModule`, `ngt-ambient-light` <-> `NgtAmbientLightModule` etc...

**Comment by IRobot1** [comment]
For most other elements, when a module is missing, the app won't compile.  But in some cases, the application appears to run, but has hard to track down problems like this one.

Modularization is great.  There's just a lot to keep track of.

**Comment by nartc** [comment]
@IRobot1 I understand. Though this is a thing with DX vs Maintainability (tradeoff) kinda thing. I can explain more if you'd like :D
