### ISSUE TITLE
[Feature] enable/disable physics on an object

### ISSUE THREAD

**Issue by nartc** [nartc/angular-three#59]
### Discussed in https://github.com/nartc/angular-three/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **IRobot1** February 19, 2022</sup>
In VR, I'd like to grab a object.  If it has physics enabled, I'd like to disable it until I release the object.

I was looking at NgtPhysicsStore, but not sure how to use it.</div>

This isn't supported at the moment.

**Comment by nartc** [comment]
@IRobot1 do you have an example of this?

**Comment by IRobot1** [comment]
I think the best way to achieve this is to use sleep and wake up.

```typescript
  @Input() set enabled(newvalue: boolean) {
    if (newvalue)
      this.physics.api.wakeUp();
    else
      this.physics.api.sleep();
  }
```
Here's the [full code example](https://github.com/IRobot1/ng3-cannon-template/blob/master/src/app/components/storybook-cube.component.ts)

[DEMO here](https://ng3cannon.z9.web.core.windows.net/), select Conditional example
