### ISSUE TITLE
[Feature] Add enable Input to ngt-cannon-debug

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#62]
Add enable Input to ngt-cannon-debug so that when false, its easy to disable without having to remove from markup.  Default is true.

<ngt-cannon-debug [enable]="false" [scale]="1.1" color="black">
...
</ngt-cannon-debug>

**Comment by nartc** [comment]
This seems trivial enough. Would you like to make a PR?

**Comment by IRobot1** [comment]
I took a look at your build environment.  Looks like its setup for Linux and there's several tools I'm not familiar with.

For now, I'm going to pass.  It would distract me from what I'm really trying to accomplish with the library.
