### ISSUE TITLE
Issues importing from '@angular-three/soba/controls'

### ISSUE THREAD

**Issue by aminica** [nartc/angular-three#68]
Hi!

When trying to import any module from '@angular-three/soba/controls' I get following compiler errors coming from threejs:

![Screenshot 2022-03-07 at 20 18 33](https://user-images.githubusercontent.com/36920828/157102738-92458c1e-f272-49a7-9318-fcd849b0aa0c.png)

My `package.json` looks like this:

![Screenshot 2022-03-07 at 20 21 21](https://user-images.githubusercontent.com/36920828/157103281-495e6fd6-4530-4c90-beff-d2a9f25df5f5.png)

Any ideas on how I could solve this? Thank you very much in advance!

**Comment by nartc** [comment]
Can you show me your tsconfig?

**Comment by aminica** [comment]
> Can you show me your tsconfig?

Sure! Thanks!

![Screenshot 2022-03-07 at 21 18 35](https://user-images.githubusercontent.com/36920828/157111494-dc9bf671-e6f4-4ba7-847d-55fba4fc8f1f.png)

**Comment by aminica** [comment]
> > Can you show me your tsconfig?
> 
> Sure! Thanks!
> 
> ![Screenshot 2022-03-07 at 21 18 35](https://user-images.githubusercontent.com/36920828/157111494-dc9bf671-e6f4-4ba7-847d-55fba4fc8f1f.png)

Ohhh "skipLibCheck" was missing! Solved, thanks for the hint!
