### ISSUE TITLE
ThreeJS r139 update

### ISSUE THREAD

**Issue by BenLune** [nartc/angular-three#79]
Hi,
Is it possible to update ThreeJS to the last version please?
Thank you!
Benoît

**Comment by BenLune** [comment]
Here is the error I have when upgrading ThreeJS to 139, using current version of angularThree : 
./node_modules/three-stdlib/nodes/core/NodeBuilder.js:470:17-40 - Error: export 'CubeUVRefractionMapping' (imported as 'CubeUVRefractionMapping') was not found in 'three'

**Comment by IRobot1** [comment]
Version 5 (currently in beta) has been updated to support 3js 139.
