### ISSUE TITLE
Compilation Warn: Add only entry points to the 'files' or 'include' properties in your tsconfig.

### ISSUE THREAD

**Issue by gmanojisaac** [nartc/angular-three#81]
Warning: C:/Users/hp/OneDrive/Desktop/Manoj/2022/Apr/gitexample/node_modules/@angular-three/cannon/esm2020/lib/utils/props-to-body.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Users/hp/OneDrive/Desktop/Manoj/2022/Apr/gitexample/node_modules/@angular-three/cannon/esm2020/lib/utils/worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Users/hp/OneDrive/Desktop/Manoj/2022/Apr/gitexample/node_modules/@angular-three/cannon/fesm2020/utils/props-to-body.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Users/hp/OneDrive/Desktop/Manoj/2022/Apr/gitexample/node_modules/@angular-three/cannon/fesm2020/utils/worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

**As per your instructions:**
ng add [@angular-three](https://githubmemory.com/@angular-three)/schematics

to add Angular Three to your project. Then to add cannon, just run the generator:

ng g [@angular-three](https://githubmemory.com/@angular-three)/schematics:cannon

You don't need to install cannon-es yourself. This is to minimize the possible conflicts between libraries' versions.

**Used angular cli - "@angular/cli": "~13.2.0",**

Please giveus the stackblitz Angular starter with the latest cannon/soba/core sub modules so that we can just download start working on the features.. I am a mid level programmer and already i have spend 1 week to reach this point.. Thanks a lot for your effort and service..

**Comment by IRobot1** [comment]
Those warnings can be ignored.

[This template](https://github.com/IRobot1/ng3-cannon-template) has the latest and lots of examples using cannon (which you can just remove) for your project.

It started out as a simple starter template.  But when I realized there were not too many examples using ng3/cannon, I figured it was better to add them.

Hope that's what you are looking for

**Comment by nartc** [comment]
This is no longer an issue with v5
