### ISSUE TITLE
[Feature] Access to Cannon Heighfield shape methods

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#82]
I'm trying to convert [cannon-es heighfield example](https://pmndrs.github.io/cannon-es/examples/heightfield) using ng3

The [Cannon Heightfield Shape](https://pmndrs.github.io/cannon-es/docs/classes/Heightfield.html) has several methods that can be used to create/generate a matching BufferGeometry.  The methods are not accessible via NgtPhysicHeightfield.  Specifically, the getConvexTrianglePillar method

The physics part when viewed with debugging enabled looks okay.  
![image](https://user-images.githubusercontent.com/25032599/162592567-757c58d2-a4ff-4130-8624-19fd52b2f3a2.png)

However, getting the right geometry to add to a mesh is proving difficult.

**Comment by nartc** [comment]
As React Cannon has this example (https://cannon.pmnd.rs/#/demo/Heightfield), I think we don't need to change the API. I'll make the example later today

**Comment by nartc** [comment]
Height field example ported:
- [code](https://github.com/nartc/angular-three/blob/main/apps/sandbox/src/app/height-field/height-field.component.ts)
- [example](https://angular-three.netlify.app/examples/height-field)

**Comment by IRobot1** [comment]
HeightFieldGeometry works like a charm.  I recommend added to the core library and reference the example on how to setup the heights.

**Comment by nartc** [comment]
@IRobot1 Not sure if it's generic enough to add to one of the libraries (I'm thinking soba/abstractions).
