### ISSUE TITLE
[V5 beta] No directive found with exportAs 'ngtPlaneGeometry'.

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#91]
Using V5 beta, error NG8003: No directive found with exportAs 'ngtPlaneGeometry'.

```html
     <ngt-plane-geometry #plane="ngtPlaneGeometry"
```

There are may other examples where variable type like ngtPlaneGeometry is no longer available.

**Comment by IRobot1** [comment]
Here's other examples, 

```html
<ngt-instanced-mesh #inst="ngtInstancedMesh" (ready)="ready(inst.mesh)"
<ngt-mesh #drag="ngtMesh" (ready)="cubeready(drag.mesh)"
```

**Comment by nartc** [comment]
All NGT classes are now Component rather than Directive, `exportAs` isn't needed anymore.

**Comment by IRobot1** [comment]
Can you show how the above examples should now work?

**Comment by nartc** [comment]
```html
<ngt-plane-geometry #plane></ngt-plane-geometry>
<ngt-mesh-standard-material #standard></ngt-mesh-standard-material>

<ngt-mesh [geometry]="plane.instance" [material]="standard.instance"></ngt-mesh>
```

**Comment by nartc** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/25516557/163728951-5bc635ad-d86b-4be0-abcb-775b54b012b9.png">
I was just working on that section of the migration guide so I use this example as well.
