### ISSUE TITLE
[V5 beta] No inputs were found in config file '.../tsconfig.worker.json'. 

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#92]
Specified 'include' paths were '["./node_modules/@angular-three/cannon/**/worker.ts","./node_modules/@angular-three/cannon/**/props-to-body.ts"]' and 'exclude' paths were '["./out-tsc/worker"]'.

This is the current contents of this file

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/worker",
    "lib": [
      "es2018",
      "webworker"
    ],
    "types": []
  },
  "include": [
    "./node_modules/@angular-three/cannon/**/worker.ts",
    "./node_modules/@angular-three/cannon/**/props-to-body.ts"
  ]
}

**Comment by nartc** [comment]
`@angular-three/cannon` is now using `pmndrs/cannon-worker-api` and does not have to ship its own Worker anymore. You can safely remove `tsconfig.worker.ts` and all references to it. There will be automatic schematics to do this down the road when v5 is almost there.

**Comment by IRobot1** [comment]
Looks like I now have to include pmndrs/cannon-worker-api to my project

I used to be able to pass DefaultContactMaterial to ngt-physics defaultContactMaterial.  However, ContactMaterialOptions now comes from the cannon-worker-api.
