### ISSUE TITLE
[V5 beta]  Can't bind to 'vr' since it isn't a known property of 'ngt-canvas'.

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#93]
```html
<ngt-canvas [vr]="vr"
```
Is there a new way to enable vr in the canvas?

**Comment by nartc** [comment]
I'm writing up some docs for v5 beta right now. `vr` has been renamed to `xr`

**Comment by IRobot1** [comment]
Hmm.  I tried changing it.  Error now changes to 

Can't bind to 'xr' since it isn't a known property of 'ngt-canvas'.

**Comment by nartc** [comment]
Well, `xr` is a tracking state but v5 should automatically switch to use WebXR when a VR session is requested. Can you try removing the `xr` input altogether?

**Comment by IRobot1** [comment]
Yes, that works.
