### ISSUE TITLE
[V5 beta] ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[NgtStore -> NgtStore -> NgtStore]:    NullInjectorError: No provider for NgtStore!

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#94]
As soon as I add NgtPhysicBody to a component, I get the NullInjectorError.  Feels like I'm missing an import module, but not sure which.

```typescript
@Component({
  templateUrl: './bounce.component.html',
  providers: [NgtPhysicBody],
})
export class BounceComponent {
  constructor(private physicBody: NgtPhysicBody) { }
}
```

**Comment by nartc** [comment]
This component needs to be inside of <ngt-canvas>

**Comment by IRobot1** [comment]
Looks like your comment was truncated

**Comment by nartc** [comment]
The component needs to be inside of ngt-physics which needs to be inside of ngt-canvas.

**Comment by IRobot1** [comment]
It is.  All of my components where working with V4.  Here's the full code for the bounce example.

```html
<div style="height:100vh">
  <ngt-canvas [camera]="{ position: [10, 2, 0], fov: 45, near:1, far:100 }"
              [scene]="{ background: 'gray' | color }">
    <ngt-directional-light [args]="['white' | color, 1.75]"
                           [position]="[20, 20, 20]" [castShadow]="true">
    </ngt-directional-light>

    <ngt-physics>
      <ngt-cannon-debug [disabled]="true" [scale]="1.1" color="red">

        <ngt-mesh [ref]="sphere1Props.ref" [castShadow]="true">
          <ngt-sphere-geometry></ngt-sphere-geometry>
          <ngt-mesh-standard-material [parameters]="{ color: 'red' | color }"></ngt-mesh-standard-material>
        </ngt-mesh>

        <ngt-mesh [ref]="sphere2Props.ref" [castShadow]="true">
          <ngt-sphere-geometry></ngt-sphere-geometry>
          <ngt-mesh-standard-material [parameters]="{ color: 'white' | color }"></ngt-mesh-standard-material>
        </ngt-mesh>

        <ngt-mesh [ref]="sphere3Props.ref" [castShadow]="true">
          <ngt-sphere-geometry></ngt-sphere-geometry>
          <ngt-mesh-standard-material [parameters]="{ color: 'blue' | color }"></ngt-mesh-standard-material>
        </ngt-mesh>

        <floor></floor>
      </ngt-cannon-debug>
    </ngt-physics>

    <ngt-soba-orbit-controls></ngt-soba-orbit-controls>
    <ngt-stats></ngt-stats>
  </ngt-canvas>
</div>
```

```typescript
import { Component } from "@angular/core";

import { NgtPhysicBody } from "@angular-three/cannon/bodies";
import { NgtTriple } from "@angular-three/core";

@Component({
  templateUrl: './bounce.component.html',
  providers: [NgtPhysicBody],
})
export class BounceComponent {

  sphere1Props = this.physicBody.useSphere(() => ({
    mass: 1,
    position: [-3, 5, 3] as NgtTriple,
    material: { restitution: 0.4 },
  }));

  sphere2Props = this.physicBody.useSphere(() => ({
    mass: 1,
    position: [-3, 5, 0] as NgtTriple,
    material: { restitution: 0.6 },
  }));

  sphere3Props = this.physicBody.useSphere(() => ({
    mass: 1,
    position: [-3, 5, -3] as NgtTriple,
    material: { restitution: 0.8 },
  }));

  constructor(private physicBody: NgtPhysicBody) { }
}

```

**Comment by IRobot1** [comment]
I added the following to AppModule, now the error changes to NullInjectorError: R3InjectorError(AppModule)[NgtStore -> ElementRef -> ElementRef -> ElementRef]

```typescript
  providers: [NgtStore],
```

**Comment by IRobot1** [comment]
I've pushed the full [cannon examples project to a v5 branch](https://github.com/IRobot1/ng3-cannon-template/tree/v5).  Hopefully, it will repeat for you.

**Comment by nartc** [comment]
I'm outside right now. can you see if you can replicate the error on the physic-cubes example in apps/sandbox on the v5 branch?

**Comment by IRobot1** [comment]
What's the command to run this standbox server?

**Comment by IRobot1** [comment]
Figure it out.  nx serve standbox

**Comment by nartc** [comment]
I think I see the problem. Your BounceComponent also includes the ngt-canvas which makes BounceComponent a parent (host) of NgtCanvas, not children. 

Why don't you just bring the three spheres into the Bounce component instead of the whole canvas?

**Comment by IRobot1** [comment]
This is the whole example page.  This worked fine in V4.

Sound like if I want to pull NgtPhysicBody into a component, that component can't include ngt-canvas

**Comment by IRobot1** [comment]
As soon as I add those two lines to SandboxPhysicCubesComponent component, it starts failing in the same way.

```typescript
@Component({
  selector: 'sandbox-physic-cubes',
  template: `
<div style="height:100vh">
        <ngt-canvas
            [dpr]="[1, 2]"
            [gl]="{ alpha: false }"
            [camera]="{ position: [-1, 5, 5], fov: 45 }">
       
            <ngt-ambient-light></ngt-ambient-light>
            <ngt-directional-light [position]="10" [castShadow]="true">
            </ngt-directional-light>

            <ngt-physics>
                <sandbox-plane [position]="[0, -2.5, 0]"></sandbox-plane>
                <sandbox-cube [position]="[0.1, 5, 0]"></sandbox-cube>
                <sandbox-cube [position]="[0, 10, -1]"></sandbox-cube>
                <sandbox-cube [position]="[0, 20, -2]"></sandbox-cube>
            </ngt-physics>
        </ngt-canvas>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [NgtPhysicBody],
})
export class SandboxPhysicCubesComponent {
  constructor(private physicBody: NgtPhysicBody) { }
}
```

Can you confirm this is the path forward for V5?  
Does this only apply for objects with physics enabled?

**Comment by nartc** [comment]
Correct. That's how DI works. In v4, the physic body directives get attached on the mesh which are children of the Canvas. In v5, the PhysicBody service needs to be a child of Canvas. Your wrapper component wraps the Canvas which makes your component the Canvas's parent.

**Comment by IRobot1** [comment]
Ok, I'll split all my examples into two components.

Hopefully, that subtly can be captured in your updated documentation.

Once I have everything migrated, I'll make some V4 to V5 migration notes based on my own experience.

**Comment by nartc** [comment]
Please do! And definitely lemme know any feedback at all as we can make changes now if needed:
- the whole Ref thing
- Attaching (I'll write more about this when I get on my laptop)
- BooleanInput (I'll write more about this when I get in my laptop)
- Material with individual inputs instead of parameters object

**Comment by nartc** [comment]
@IRobot1 here's my list so far https://github.com/nartc/angular-three/blob/v5/libs/documentations/docs/getting-started/migrate-to-v5.mdx

**Comment by IRobot1** [comment]
Can you give an example of how to use instanced mesh with physics?  Its not clear to me how ref is applied to each instance.

Previously the following code worked, but now throws lots of errors in the tick method

```typescript
  count = 400;

  private boxes: Array<NgtTriple> = []

  constructor(private physicBody: NgtPhysicBody) {
    for (let i = 0; i < this.count; i++) {
      // start with random positions
      this.boxes.push([
        (Math.random() * 2 - 1) * 5,
        Math.random() * 10,
        (Math.random() * 2 - 1) * 5
      ])
    }
  }

  cubeProps = this.physicBody.useBox((index: number) => ({
    mass: 1,
    position: this.boxes[index],
    args: [1, 1, 1],
  }));

  ready(inst: InstancedMesh) {
    for (let i = 0; i < this.count; i++) {
      inst.setColorAt(i, new Color().setHex(Math.random() * 0xffffff));
    }
  }

  tick() {
    const index = Math.floor(Math.random() * this.count)
    this.cubeProps.api.at(index).position.set(0, 5 + Math.random() * 15, 0);
  }```

`Uncaught TypeError: Cannot read properties of undefined (reading 'position')`

Looks like at(index) no longer returns a valid object

**Comment by nartc** [comment]
@IRobot1 There's a bug with InstancedMesh. I just released beta.2 that contains the fix. I also added the Kinematic Cube example to the sandbox. Please take a look

**Comment by IRobot1** [comment]
I confirmed instance mesh is now fixed with beta 2.

**Comment by nartc** [comment]
@IRobot1 https://github.com/nartc/angular-three/issues/96 can you chime in here all the findings that you've found so far?
