### ISSUE TITLE
[V5 beta] cannon-debug always enabled

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#95]
```html
<ngt-cannon-debug [disabled]="true" [scale]="1.1" color="black">
```

Its visible when disabled is true.  Is this feature missing from V5?

**Comment by nartc** [comment]
a bug :( beta.4 has been released to fix this. Btw, you can do this:

```html
<ngt-cannon-debug disabled scale="1.1" color="black"></ngt-cannon-debug>
```

`BooleanInput` and `NumberInput` should allow that to work. You should only use `[]` binding syntax when the value is dynamic.
