### ISSUE TITLE
[V5 beta] TypeError: Cannot read properties of undefined (reading 'dispatchEvent')

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#97]
My V5 version of physics examples is [here](https://ng3cannon.z9.web.core.windows.net/)

Whenever I switch between examples (choose in left panel), the follow error appears in the browser console.

THREE.Scene: .dispose() has been removed.
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'dispatchEvent')
TypeError: Cannot read properties of undefined (reading 'dispatchEvent')

This didn't happen in V4.

**Comment by nartc** [comment]
It's a bug and I'm not sure if I fixed it. I just published beta.6. Can you give it a try? And this is probably the last bug fix beta for the day as I'm gonna do some work :D

**Comment by IRobot1** [comment]
Beta 8 fixes that and other similar problems I was seeing.  All the physics examples I had working in V4 are now working in V5.

Thanks for all your help today.

I'm now going to finish working on the remaining constraints examples.
