### ISSUE TITLE
[Feature] cannon constraint equation multiplier

### ISSUE THREAD

**Issue by IRobot1** [nartc/angular-three#98]
While converting cannon-es [tear example](https://github.com/pmndrs/cannon-es/blob/master/examples/tear.html#L63), the code accesses the equations property and multiplier.

According to the [cannon documentation](https://pmndrs.github.io/cannon-es/docs/classes/Constraint.html#equations), this properly is common to all constraints.

This is a request to add support for accessing either the equations and/or multiplier value.

If there another way to get multiplier value  using existing features, let me know.

**Comment by nartc** [comment]
I think there should be a way to get the data. The problem is that we're using Cannon Worker API which is a Web Worker implementation. The data, if available at all, would be in asynchronous state. 

Can you look at https://cannon.pmnd.rs/ and see if there's any example that might be similar to tear?

**Comment by IRobot1** [comment]
There might be an existing way to achieve this.  Looks like there's a multiplier that can be declared with the constraint.  I'll investigate using that and follow up.

**Comment by IRobot1** [comment]
Adjust the maxMultiplier value on distance contraint.  Higher values make the bonds/links between bodies stronger

```typescript
        const constraint = this.physicConstraint.useDistanceConstraint(body.ref, lastBody.ref, {
          distance: this.distance,
          maxMultiplier: 1000, // higher multiplier makes links stronger
        })
```
